name: CI - Test bn Utility

on:							
  push:
    branches: [ "main" ]			

jobs:
  build:						
    runs-on: ubuntu-latest			
    steps:
      - uses: actions/checkout@v4

      - name: Make the script executable
        run: chmod +x ./test_script        

      - name: Run Tests			
        run: ./test_script > test_results.txt		

      - name: Upload Test Results
        if: ${{ always() }}        
        uses: actions/upload-artifact@v4	
        with:
          name: Test Results		
          path: ./test_results.txt     
